sudo: required
services:
  - docker

before_install:
  - docker build -t devstbz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run devstbz/react-test npm test -- --coverage


after_success:
  - docker build -t devstbz/multi-client ./client
  - docker build -t devstbz/multi-nginx ./nginx
  - docker build -t devstbz/multi-server ./server
  - docker build -t devstbz/multi-worker ./worker
  # Log into the docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push devstbz/multi-client
  - docker push devstbz/multi-nginx
  - docker push devstbz/multi-server
  - docker push devstbz/multi-worker


deploy:
  provider: "elasticbeanstalk"
  region: "us-west-2"
  app: "docker-proact"
  env: "DockerProact-env"
  bucket_name: "elasticbeanstalk-us-west-2-323216669271"
  bucket_path: "docker-proact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY