sudo: required
services:
  - docker

before_install:
  - docker build -t csilva/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run csilva/react-test npm test -- --coverage


after_success:
  - docker build -t csilva/multi-client ./client
  - docker build -t csilva/multi-nginx ./nginx
  - docker build -t csilva/multi-server ./server
  - docker build -t csilva/multi-worker ./worker
  # Log into the docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --p-stdin

  - docker push csilva/multi-client
  - docker push csilva/multi-nginx
  - docker push csilva/multi-server
  - docker push csilva/multi-worker